version: 0.2

phases:
  pre_build:
    commands:
      # Authenticate Docker client to ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 591802062023.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      # Build Docker image
      - docker build -t nodejsapp22 .

  post_build:
    commands:
      # Tag the image
      - docker tag nodejsapp22:latest 591802062023.dkr.ecr.us-east-1.amazonaws.com/nodejsapp22:latest
      # Push the image to ECR
      - docker push 591802062023.dkr.ecr.us-east-1.amazonaws.com/nodejsapp22:latest

artifacts:
  files: []

